root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  full_bin = "..."
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  log = "build-errors.log"
  stop_on_error = true

[log]
  time = false

[screen]
  clear_on_rebuild = true

[misc]
  clean_on_exit = true
